server:
  port: 8061

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/panhb/spring-cloud-demo.git
          search-paths: config-repo
          username: 391400311@qq.com
          password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
  instance:
    preferIpAddress: true

management :
  security :
    enabled : false
