server:
  port: 8021

spring:
  application:
    name: microservice-consumer-ribbon

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
  instance:
    preferIpAddress: true