server :
  port : 8001 # 指定该Eureka实例的端⼝

spring :
  application :
    name : microservice-eureka

eureka :
  instance :
    hostname : peer1 # 指定该Eureka实例的主机名
  client :
    #registerWithEureka : false
    #fetchRegistry : false
    #serviceUrl :
      #defaultZone : http://${eureka.instance.hostname}:${server.port}/eureka/
    serviceUrl :
      defaultZone : http://peer2:8002/eureka/