server:
  port: 8022

spring:
  application:
    name: microservice-consumer-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
  instance:
    preferIpAddress: true

ribbon:
  eureka:
    enabled: true