server:
  port: 9000

spring:
  application:
    name: microservice-sleuth-zipkin
  sleuth:
    enabled: false
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://127.0.0.1:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: ALWAYS
    continue-on-error: true

zipkin:
  storage:
    type: mysql

management:
   metrics:
      web:
         server:
            auto-time-requests: false

